### ISSUE TITLE
ステータスの管理もAPIを作って欲しい(discord)

### ISSUE THREAD

**Issue by kinoko2k** [Firstmemory-Network/RPGCoreAPI#1]
API.getSkillpointはどうやって、Heatlh, Defense, Strenghthとか選ぶの？
(discordから)

**Comment by moru348** [comment]
SkillPointはステータスを割り振るポイントなのでまた別途APIを追加しました。

`API.setStatusLevel`
`API.getStatusLevel`

あと名前ややこしくて誤解招きまくってるみたいなのでSkillPointからStatusPointに変更しました。
`getSkillPoint -> getStatusPoint`
`setSkillPoint -> setStatusPoint`
