### ISSUE TITLE
HPやMPのAPIを作って欲しい

### ISSUE THREAD

**Issue by kinoko2k** [Firstmemory-Network/RPGCoreAPI#2]
MPはスキル
HPはゾンビ能力

**Comment by moru348** [comment]
MPはスタミナに変更して

==== スタミナ関連 ====
setMaxStamina
getMaxStamina
setStamina
getStamina

==== HP関連 ====
setMaxHealth
getMaxHealth
setHealth
getHealth

を追加しました。

**Comment by kinoko2k** [comment]
ok
